version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
  api:
    build: ./backend
    env_file: .env
    depends_on:
      - mongo
      - redis
    ports:
      - '4000:4000'
  web:
    build: ./frontend
    env_file: .env
    depends_on:
      - api
    ports:
      - '5173:5173'
volumes:
  mongo-data:
