#!/bin/bash

echo "GitHub Repository Push Instructions"
echo "==================================="
echo ""
echo "Since you need to authenticate, you have a few options:"
echo ""
echo "Option 1: Use GitHub CLI (Recommended)"
echo "--------------------------------------"
echo "1. First, login to GitHub CLI:"
echo "   gh auth login"
echo ""
echo "2. Then create the repository:"
echo "   gh repo create claude-runner-game --public --source=. --remote=origin --push"
echo ""
echo "Option 2: Use Personal Access Token"
echo "-----------------------------------"
echo "1. Go to https://github.com/settings/tokens"
echo "2. Generate a new token with 'repo' permissions"
echo "3. Use the token as your password when prompted:"
echo "   git push -u origin main"
echo ""
echo "Option 3: Set up SSH Keys"
echo "-------------------------"
echo "1. Generate SSH key:"
echo "   ssh-keygen -t ed25519 -C \"jvzingarelli@gmail.com\""
echo ""
echo "2. Add to SSH agent:"
echo "   eval \"\$(ssh-agent -s)\""
echo "   ssh-add ~/.ssh/id_ed25519"
echo ""
echo "3. Copy public key:"
echo "   pbcopy < ~/.ssh/id_ed25519.pub"
echo ""
echo "4. Add to GitHub: https://github.com/settings/keys"
echo ""
echo "5. Change remote to SSH:"
echo "   git remote set-url origin git@github.com:jvzingarelli/claude-runner-game.git"
echo "   git push -u origin main"